Class {
	#name : #User,
	#superclass : #Object,
	#instVars : [
		'questionRetriever',
		'questions',
		'answers',
		'username',
		'password',
		'topics',
		'following',
		'votes'
	],
	#category : #'TP-Refactoring-Model'
}

{ #category : #'instance-creation' }
User class >> username: aUsername password: aPassword questionRetriever: aQuestionRetriever [
	^ self new
		initializeWithUsername: aUsername password: aPassword questionRetriever: aQuestionRetriever;
		yourself
]

{ #category : #accessing }
User >> addQuestion: aQuestion [
	questions add: aQuestion
]

{ #category : #accessing }
User >> addTopic: aTopic [
	topics add: aTopic 

]

{ #category : #accessing }
User >> addVote: aVote [
	votes add: aVote
]

{ #category : #accessing }
User >> follow: aUser [
	following add: aUser 
]

{ #category : #accessing }
User >> following [
	^ following
]

{ #category : #initialize }
User >> initialize [

	questions := OrderedCollection new.  
	answers := OrderedCollection new. 
	topics := OrderedCollection new. 
	following := OrderedCollection new. 
	votes := OrderedCollection new.
]

{ #category : #initialize }
User >> initializeWithUsername: aUsername password: aPassword questionRetriever: aQuestionRetriever [
username :=aUsername.
password :=aPassword .
questionRetriever :=aQuestionRetriever 
]

{ #category : #accessing }
User >> questions [
	^ questions
]

{ #category : #accessing }
User >> topics [
	^ topics
]

{ #category : #accessing }
User >> votes [
	^ votes
]
